# Generated by Django 6.0.3 on 2026-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
