# Generated by Django 6.0.3 on 2026-04-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0004_alter_user_age_bloodpressurerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
