# Generated by Django 6.0.3 on 2026-04-01 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0005_remove_user_age_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpressurerecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bloodpressurerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bloodpressurerecord',
            name='diastolic',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='bloodpressurerecord',
            name='pulse',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AlterField(
            model_name='bloodpressurerecord',
            name='systolic',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
